### ISSUE TITLE
Keep timing after the app is closed

### ISSUE THREAD

**Issue by sfanxiang** [HaikuArchives/TimeTracker#20]
If the user leaves tasks running when they closes the app, the task should continue to run.

The idea is simple: record the time when the app is closed, and calculate the time elapsed when the app is opened again.

**Comment by humdingerb** [comment]
I don't think this is useful. When you close TimeTracker and the time keeps on ticking (♬ into the future ♬) you forget about that and don't remember to start TimeTracker again to stop the clock when you stop working on that silently ticking-away task.

**Comment by sfanxiang** [comment]
OK. How about showing a warning at exit?

**Comment by humdingerb** [comment]
That would be annoying, too, don't you think?
I don't see a problem with only clocking the time of the active tasks when TimeTracker is running. Usually, as people tend to multitask, you'll need to have TT running anyway, because you have to periodically start/stop tasks.
Not keeping the clock running when TT isn't running feels logical and natural.
